services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: boonafide-server
    container_name: boonafide-node-server
    command: npm run dev
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    env_file: 
      - ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    # MongoDB dependency is optional - will be ignored if mongo service isn't running

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: boonafide-client
    container_name: boonafide-react-client
    command: npm start
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

  mongo:
    image: mongo:5.0
    container_name: boonafide-mongo
    profiles:
      - database
      - full
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=boonafide
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local