name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
        env:
          HD_CLOUDINARY_KEY: ${{secrets.CLOUDINARY_KEY}}
          HD_CLOUDINARY_NAME: ${{secrets.CLOUDINARY_NAME}}
          HD_CLOUDINARY_SECRET: ${{secrets.CLOUDINARY_SECRET}}
          HD_DBURL: ${{secrets.DBURL}}
          HD_NODE_ENV: production